#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page

file="/etc/nginx/sites-enabled/default"
rep="server_name _;\n\trewrite \^\/redirect_me\$ https:\/\/youtube\.com permanent;"

#uninstall existing nginx configuration
apt-get --purge remove -y nginx && apt-get --purge autoremove -y

#update repo
apt-get update

# install nginx
apt-get install -y nginx

# create sample page
echo "Hello World!" >/var/www/html/index.nginx-debian.html

#configure web server redirection
sed -i "s/server_name\s_?;/$rep/" $file

# restart nginx
service nginx restart
