#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

file="/etc/nginx/sites-enabled/default"
rep="server_name _;\n\trewrite \^\/redirect_me\$ https:\/\/youtube\.com permanent"

sed -i "s/server_name\s_/$rep/" $file

#restart nginx
service nginx restart
