#!/usr/bin/env bash
#Configure your Nginx server with a custom 404 page

file="/etc/nginx/sites-enabled/default"
rep="server_name _;\n\terror_page 404 \/error404\.html; \
  \n\tlocation \/redirect_me \{\n\t\trewrite \^\/redirect_me https:\/\/www\.youtube\.com permanent;\n\t\}"

#update repo
apt-get update

# install nginx
apt-get install -y nginx

# create sample page
echo "Hello World!" >/var/www/html/index.nginx-debian.html

#configure web server redirection
sed -i "s/server_name\s_;/$rep/" $file

#create custom 404 page
echo "Ceci n'est pas une page" >/var/www/html/error404.html

# restart nginx
service nginx restart
