#!/usr/bin/env bash
#Write Bash (init) script 101-manage_my_process that manages manage_my#_process. (both files need to be pushed to git)
#
#Requirements:
#
#When passing the argument start:
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process started
#When passing the argument stop:
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Displays manage_my_process stopped
#When passing the argument restart
#Stops manage_my_process
#Deletes the file /var/run/my_process.pid
#Starts manage_my_process
#Creates a file containing its PID in /var/run/my_process.pid
#Displays manage_my_process restarted
#Displays Usage: manage_my_process {start|stop|restart} if any other
#argument or no argument is passed

dmn="./manage_my_process"
pidlog="/var/run/my_process.pid"
if [[ $# -eq 1 ]]
then
	case $1 in 
		"start")
			$dmn &
			if [[ -n "$!" ]]
			then
				echo "$!" >> $pidlog
				echo "manage_my_process started"
			fi
			;;
		"stop")
			if [[ -n $( pgrep -f $dmn) ]]
			then
				pkill -f $dmn
				rm $pidlog
				echo "manage_my_process stopped"
			fi
			;;
		"restart")
			if [[ -n $( pgrep -f $dmn) ]]
			then
				pkill -f $dmn
				rm $pidlog
				$dmn &
				echo "$!" >> $pidlog
				echo "manage_my_process restarted"
			fi
			;;
		*)
			echo "Usage: manage_my_process {start|stop|restart}"
			;;
	esac
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
