#!/usr/bin/env bash
#Bash script that displays lines containing the bash word
# shellcheck disable=SC2009

output=$(ps -axuf)

while read -r line
do
	if echo "$line" | grep -q 'bash'
	then
		echo "$line"
	fi
done <"$output"
