#!/usr/bin/env bash
#Write a Bash script that stops 4-to_infinity_and_beyond process.
#
#Requirements:
#
#You cannot use kill or killall

pcs="./4-to_infinity_and_beyond"
pid="$( pgrep -f $pcs )"

if [[ -n $pid ]]
then
	pkill -f "$pcs"
fi
