#!/usr/bin/env bash
#write a Bash script that groups visitors by IP and HTTP status code, #and displays this data.
#
#Requirements:
#
#The exact format must be:
#OCCURENCE_NUMBER IP HTTP_CODE
#In list format
#Ordered from the greatest to the lowest number of occurrences

snf="$( awk '{print $1 " " $9}' ./apache-access.log)"
if [[ -n $snf ]]
then
	echo "$snf" | sort | uniq -c | sort -nr
fi
