#!/usr/bin/env bash
#write a Bash script that groups visitors by IP and HTTP status code, #and displays this data.
#
#Requirements:
#
#The exact format must be:
#OCCURENCE_NUMBER IP HTTP_CODE
#In list format
#Ordered from the greatest to the lowest number of occurrences

awk '{
  a[$1" "$9]++
}
END {
  for (i in a)
    print a[i], i
}' ./apache-access.log | sort -nr | awk '{
  if (!($2" "$3 in b)) {
    print $1,$2,$3
    b[$2" "$3]=1
  }
}'

